export { default as Home } from './Home'
export { default as Page } from './Page'
export { default as Post } from './Post'
export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Search } from './Search'
